- project-template:
    name: openstack-python3-jobs-blazar-nova
    description: |
      The standard :zuul:project_template:`openstack-python-jobs` but with nova
      added as a required-projects. This checks out the project code and allows
      tox_install.sh to use nova when building the venv.
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/nova
        - openstack-tox-py39:
            required-projects:
              - openstack/nova
        - openstack-tox-py312:
            required-projects:
              - openstack/nova
    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/nova
        - openstack-tox-py39:
            required-projects:
              - openstack/nova
        - openstack-tox-py312:
            required-projects:
              - openstack/nova
    post:
      jobs:
        - publish-openstack-python-branch-tarball

- project:
    templates:
      - check-requirements
      - openstack-python3-jobs
      - openstack-python3-jobs-blazar-nova
      - release-notes-jobs-python3
