- project:
    templates:
      - check-requirements
      - openstack-python3-yoga-jobs
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-py36:
            voting: false
    gate:
      jobs:
        - openstack-tox-py36:
            voting: false
