- project-template:
    name: openstack-python3-jobs-blazar-nova
    description: |
      The standard :zuul:project_template:`openstack-python-jobs` but with nova
      added as a required-projects. This checks out the project code and allows
      tox_install.sh to use nova when building the venv.
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/nova
        - openstack-tox-py310:
            required-projects:
              - openstack/nova
        - openstack-tox-py312:
            required-projects:
              - openstack/nova
        - openstack-tox-py313:
            required-projects:
              - openstack/nova
            voting: false
    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/nova
        - openstack-tox-py310:
            required-projects:
              - openstack/nova
        - openstack-tox-py312:
            required-projects:
              - openstack/nova
    periodic:
      jobs:
        - openstack-tox-py310:
            branches:
              - master
            required-projects:
              - openstack/nova
        - openstack-tox-py311:
            branches:
              - master
            required-projects:
              - openstack/nova

- project:
    templates:
      - check-requirements
      - openstack-python3-jobs-blazar-nova
      - release-notes-jobs-python3
